### ISSUE TITLE
Actividad 3 REPORTE_DE_PRACTICA_EN_ARCHITEC

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-3-practica-architect-SandyMarissaGs#1]
[REPORTE_DE_PRACTICA_EN_ARCHITEC.pdf](https://github.com/user-attachments/files/16831383/REPORTE_DE_PRACTICA_EN_ARCHITEC.pdf)

**Comment by Roldanuriel** [comment]
20/20 Cumple con todas las descripciones de la rubrica principalmente con la visualización de la actividad

**Comment by Roldanuriel** [comment]
20/20 Describe claramente cada una de las fases de la actividad realizada y la practica e instalación de Architect

**Comment by josealfredo79** [comment]
bien hecho y revisado..
